#
# DO NOT EDIT
#
# this file is generated by running gensearchable.py in this directory
#

accounts = [
    "(auto login)",
    "Edit",
    "Remove",
    "Add Accounts",
    "My Accounts",
    "Account Options",
    "buddy list",
    "icon tray",
    "buddy list and icon tray",
    "Show email accounts in:",
    "Show social networks in:",
]

advanced = [
    "IM Window",
    "Merge Metacontact History",
    "Use Proxy Server",
    "Use Global Settings",
    "Protocol:",
    ":",
]

appearance = [
    "Application Skin",
    "Conversation Theme",
    "Conversation Preview",
    "Skin:",
    "Variant:",
    "Show header",
    "Show message fonts",
    "Show message colors",
    "Theme:",
    "Fonts:",
    "Colors:",
]

contact_list = [
    "Sorting and Groups",
    "Autohide when not in focus",
    "Automatically dock when near edge of screen",
    "Keep on top of other applications",
    "Show in taskbar",
    "Window Options",
    "Contact Layout",
    "Advanced",
    "Basic",
    "Group by:",
    "Sort by:",
    "Then by:",
    "Far Left",
    "Left",
    "Right",
    "Far Right",
    "Badge (Lower Left)",
    "Badge (Lower Right)",
    "Show buddy icon on the:",
    "Buddy icon size:",
    "Buddy padding:",
    "Show status icon on:",
    "Show service icon on:",
    "Contact name:",
    "Show extra info:",
    "Status",
    "Idle Time",
    "Idle Time + Status",
]

dev = [
    "Advanced Prefs",
    "Enable Debug Console",
    "Allow Reconnect if --start-offline",
    "Debug",
    "Digsby Protocol",
    "Append signature",
    "Email",
    "Enabled",
    "Print debug output to console. (don't use pipes)",
    "Always On",
    "Run when on battery",
    "Plura",
    "Use Global Status Dialog (may require restart)",
    "Scan tweets for URLs (for popup click action)",
    "Social accounts",
]

files = [
    "File Transfers",
    "Save files to:",
    "Create subfolders for each IM account",
    "Auto-accept all file transfers from contacts on my contact list",
]

general_profile = [
    "Launch Digsby when this computer starts",
    "Automatically download software updates",
    "If connection to IM service is lost, automatically attempt to reconnect",
    "Show trending news articles in social network feeds (powered by OneRiot)",
    "General Options",
    "Profile (AIM Only)",
    "Buddy Icon",
    "Language",
    "Change",
    "Promote Digsby in my AIM profile",
]

helpdigsby = [
    "Help Digsby",
]

notifications = [
    "bottom right corner",
    "bottom left corner",
    "top right corner",
    "top left corner",
    "Enable pop-up notifications in the ",
    " on monitor ",
    "Enable sounds",
    "Notifications",
    "Events",
    "Restore Defaults",
    "Restore Default Notifications",
]

plugins = [
]

privacy = [
    "Let others know that I am typing",
    "Automatically sign me into websites (e.g., Yahoo! Mail)",
    "Global Privacy Options",
    "You must be signed in to modify privacy settings.",
    "Sign in with \"%s\"",
    "Edit",
    "Allow all users to contact me",
    "Allow only users on my contact list",
    "Allow only users on 'Allow List'",
    "Block all users",
    "Block only users on 'Block List'",
    "Only my screen name",
    "Only that I have an account",
    "Nothing about me",
    "Permissions",
    "Options",
    "Allow only users on my buddy list to contact me",
    "Require authorization before users can add me to their contact list",
    "Block authorization requests with URLs in them",
    "Allow others to view my online status from the web",
    "Allow unknown users to contact me",
    "%s is on your buddylist. Do you want to remove %s from your buddylist and block the user?",
    "Confirm Block and Remove",
    "Nothing to see here. If you do see this, this is either a special dev-only account, or something is broken.",
]

proxy = [
]

status = [
    "Status Options",
    "Promote Digsby in my IM status messages",
    "Let others know that I am idle after %2(messaging.idle_after)d minutes of inactivity",
    "Autorespond with status message",
    "Disable sounds",
    "Disable pop-up notifications",
    "When away...",
    "Hide new conversation windows",
    "Disable sounds",
    "Disable popup notifications",
    "When running full screen applications...",
    "Status Messages",
]

supportdigsby = [
    "Support Digsby",
]

text_conversations = [
    "automatically take focus",
    "start minimized in taskbar",
    "start hidden (tray icon blinks)",
    "bottom",
    "top",
    "left",
    "right",
    "Keep on top of other applications",
    "Group multiple conversations into one tabbed window",
    "New conversation windows: ",
    "buddy icon",
    "service icon",
    "status icon",
    "Identify conversations with the contact's: ",
    "Window Options",
    "Conversation Options",
    "Don't show flash ads",
    "Support Digsby development with an ad",
    "Location of ad in IM window: ",
    "Ad Options",
    "Text Formatting",
    "Your messages will look like this.",
    "Show last %2(conversation_window.num_lines)d lines in IM window",
    "Display timestamp:",
    "Spell check:",
    "Log IM conversations to hard drive",
    "Show emoticons:",
]

