codes =  {          0 : u'',
                    1 : u'USA',
                    7 : u'Russia',
                    20 : u'Egypt',
                    27 : u'South Africa',
                    30 : u'Greece',
                    31 : u'Netherlands',
                    32 : u'Belgium',
                    33 : u'France',
                    34 : u'Spain',
                    36 : u'Hungary',
                    39 : u'Italy',
                    40 : u'Romania',
                    41 : u'Switzerland',
                    42 : u'Czech Republic',
                    43 : u'Austria',
                    44 : u'United Kingdom',
                    45 : u'Denmark',
                    46 : u'Sweden',
                    47 : u'Norway',
                    48 : u'Poland',
                    49 : u'Germany',
                    51 : u'Peru',
                    52 : u'Mexico',
                    53 : u'Cuba',
                    54 : u'Argentina',
                    55 : u'Brazil',
                    56 : u'Chile',
                    57 : u'Colombia',
                    58 : u'Venezuela',
                    60 : u'Malaysia',
                    61 : u'Australia',
                    62 : u'Indonesia',
                    63 : u'Philippines',
                    64 : u'New Zealand',
                    65 : u'Singapore',
                    66 : u'Thailand',
                    81 : u'Japan',
                    82 : u'Korea (Republic of)',
                    84 : u'Vietnam',
                    86 : u'China',
                    90 : u'Turkey',
                    91 : u'India',
                    92 : u'Pakistan',
                    93 : u'Afghanistan',
                    94 : u'Sri Lanka',
                    95 : u'Myanmar',
                    98 : u'Iran',
                    101 : u'Anguilla',
                    102 : u'Antigua',
                    103 : u'Bahamas',
                    104 : u'Barbados',
                    105 : u'Bermuda',
                    106 : u'British Virgin Islands',
                    107 : u'Canada',
                    108 : u'Cayman Islands',
                    109 : u'Dominica',
                    110 : u'Dominican Republic',
                    111 : u'Grenada',
                    112 : u'Jamaica',
                    113 : u'Montserrat',
                    114 : u'Nevis',
                    115 : u'St. Kitts',
                    116 : u'St. Vincent and the Grenadines',
                    117 : u'Trinidad and Tobago',
                    118 : u'Turks and Caicos Islands',
                    120 : u'Barbuda',
                    121 : u'Puerto Rico',
                    122 : u'Saint Lucia',
                    123 : u'United States Virgin Islands',
                    212 : u'Morocco',
                    213 : u'Algeria',
                    216 : u'Tunisia',
                    218 : u'Libya',
                    220 : u'Gambia',
                    221 : u'Senegal Republic',
                    222 : u'Mauritania',
                    223 : u'Mali',
                    224 : u'Guinea',
                    225 : u'Ivory Coast',
                    226 : u'Burkina Faso',
                    227 : u'Niger',
                    228 : u'Togo',
                    229 : u'Benin',
                    230 : u'Mauritius',
                    231 : u'Liberia',
                    232 : u'Sierra Leone',
                    233 : u'Ghana',
                    234 : u'Nigeria',
                    235 : u'Chad',
                    236 : u'Central African Republic',
                    237 : u'Cameroon',
                    238 : u'Cape Verde Islands',
                    239 : u'Sao Tome and Principe',
                    240 : u'Equatorial Guinea',
                    241 : u'Gabon',
                    242 : u'Congo',
                    243 : u'Dem. Rep. of the Congo',
                    244 : u'Angola',
                    245 : u'Guinea-Bissau',
                    246 : u'Diego Garcia',
                    247 : u'Ascension Island',
                    248 : u'Seychelle Islands',
                    249 : u'Sudan',
                    250 : u'Rwanda',
                    251 : u'Ethiopia',
                    252 : u'Somalia',
                    253 : u'Djibouti',
                    254 : u'Kenya',
                    255 : u'Tanzania',
                    256 : u'Uganda',
                    257 : u'Burundi',
                    258 : u'Mozambique',
                    260 : u'Zambia',
                    261 : u'Madagascar',
                    262 : u'Reunion Island',
                    263 : u'Zimbabwe',
                    264 : u'Namibia',
                    265 : u'Malawi',
                    266 : u'Lesotho',
                    267 : u'Botswana',
                    268 : u'Swaziland',
                    269 : u'Mayotte Island',
                    290 : u'St. Helena',
                    291 : u'Eritrea',
                    297 : u'Aruba',
                    298 : u'Faeroe Islands',
                    299 : u'Greenland',
                    350 : u'Gibraltar',
                    351 : u'Portugal',
                    352 : u'Luxembourg',
                    353 : u'Ireland',
                    354 : u'Iceland',
                    355 : u'Albania',
                    356 : u'Malta',
                    357 : u'Cyprus',
                    358 : u'Finland',
                    359 : u'Bulgaria',
                    370 : u'Lithuania',
                    371 : u'Latvia',
                    372 : u'Estonia',
                    373 : u'Moldova',
                    374 : u'Armenia',
                    375 : u'Belarus',
                    376 : u'Andorra',
                    377 : u'Monaco',
                    378 : u'San Marino',
                    379 : u'Vatican City',
                    380 : u'Ukraine',
                    381 : u'Yugoslavia',
                    385 : u'Croatia',
                    386 : u'Slovenia',
                    387 : u'Bosnia and Herzegovina',
                    389 : u'F.Y.R.O.M. (Former Yugoslav Republic of Macedonia)',
                    421 : u'Slovakia',
                    500 : u'Falkland Islands',
                    501 : u'Belize',
                    502 : u'Guatemala',
                    503 : u'El Salvador',
                    504 : u'Honduras',
                    505 : u'Nicaragua',
                    506 : u'Costa Rica',
                    507 : u'Panama',
                    508 : u'St. Pierre and Miquelon',
                    509 : u'Haiti',
                    590 : u'Guadeloupe',
                    591 : u'Bolivia',
                    592 : u'Guyana',
                    593 : u'Ecuador',
                    594 : u'French Guiana',
                    595 : u'Paraguay',
                    596 : u'Martinique',
                    597 : u'Suriname',
                    598 : u'Uruguay',
                    599 : u'Netherlands Antilles',
                    670 : u'Saipan Island',
                    671 : u'Guam',
                    672 : u'Christmas Island',
                    673 : u'Brunei',
                    674 : u'Nauru',
                    675 : u'Papua New Guinea',
                    676 : u'Tonga',
                    677 : u'Solomon Islands',
                    678 : u'Vanuatu',
                    679 : u'Fiji Islands',
                    680 : u'Palau',
                    681 : u'Wallis and Futuna Islands',
                    682 : u'Cook Islands',
                    683 : u'Niue',
                    684 : u'American Samoa',
                    685 : u'Western Samoa',
                    686 : u'Kiribati Republic',
                    687 : u'New Caledonia',
                    688 : u'Tuvalu',
                    689 : u'French Polynesia',
                    690 : u'Tokelau',
                    691 : u'Micronesia, Federated States of',
                    692 : u'Marshall Islands',
                    705 : u'Kazakhstan',
                    706 : u'Kyrgyz Republic',
                    708 : u'Tajikistan',
                    709 : u'Turkmenistan',
                    711 : u'Uzbekistan',
                    800 : u'International Freephone Service',
                    850 : u'Korea (North)',
                    852 : u'Hong Kong',
                    853 : u'Macau',
                    855 : u'Cambodia',
                    856 : u'Laos',
                    870 : u'INMARSAT',
                    871 : u'INMARSAT (Atlantic-East)',
                    872 : u'INMARSAT (Pacific)',
                    873 : u'INMARSAT (Indian)',
                    874 : u'INMARSAT (Atlantic-West)',
                    880 : u'Bangladesh',
                    886 : u'Taiwan, Republic of China',
                    960 : u'Maldives',
                    961 : u'Lebanon',
                    962 : u'Jordan',
                    963 : u'Syria',
                    964 : u'Iraq',
                    965 : u'Kuwait',
                    966 : u'Saudi Arabia',
                    967 : u'Yemen',
                    968 : u'Oman',
                    971 : u'United Arab Emirates',
                    972 : u'Israel',
                    973 : u'Bahrain',
                    974 : u'Qatar',
                    975 : u'Bhutan',
                    976 : u'Mongolia',
                    977 : u'Nepal',
                    994 : u'Azerbaijan',
                    995 : u'Georgia',
                    2691 : u'Comoros',
                    4101 : u'Liechtenstein',
                    4201 : u'Slovak Republic',
                    5399 : u'Guantanamo Bay',
                    5901 : u'French Antilles',
                    6101 : u'Cocos-Keeling Islands',
                    6701 : u'Rota Island',
                    6702 : u'Tinian Island',
                    6721 : u'Australian Antarctic Territory',
                    6722 : u'Norfolk Island',
                    9999 : u'Unknown',
                    }
