import os
import wx

# ordered for modifier entries in menus
modifiernames = [
    (wx.ACCEL_CTRL, 'Ctrl'),
    (wx.ACCEL_ALT, 'Alt'),
    (wx.ACCEL_SHIFT, 'Shift'),
#   (wx.ACCEL_CMD, 'Ctrl'),
]

keynames = {
    wx.WXK_MENU: 'Menu',
    wx.WXK_NUMPAD_TAB: 'Numpad Tab',
    wx.WXK_NUMPAD_SEPARATOR: 'Numpad Separator',
    wx.WXK_SNAPSHOT: 'Snapshot',
    wx.WXK_DOWN: 'Down',
    wx.WXK_CLEAR: 'Clear',
    wx.WXK_ALT: 'Alt',
    wx.WXK_COMMAND: 'Command',
    wx.WXK_SPECIAL2: 'Special2',
    wx.WXK_INSERT: 'Insert',
    wx.WXK_NUMPAD_DECIMAL: 'Numpad Decimal',
    wx.WXK_SHIFT: 'Shift',
    wx.WXK_NEXT: 'Next',
    wx.WXK_SCROLL: 'Scroll',
    wx.WXK_CAPITAL: 'Capital',
    wx.WXK_NUMPAD_HOME: 'Numpad Home',
    wx.WXK_SPECIAL8: 'Special8',
    wx.WXK_SPECIAL9: 'Special9',
    wx.WXK_SPECIAL1: 'Special1',
    wx.WXK_SPECIAL3: 'Special3',
    wx.WXK_SPECIAL4: 'Special4',
    wx.WXK_SPECIAL5: 'Special5',
    wx.WXK_SPECIAL6: 'Special6',
    wx.WXK_SPECIAL7: 'Special7',
    wx.WXK_SPACE: 'Space',
    wx.WXK_SELECT: 'Select',
    wx.WXK_PAGEDOWN: 'Pagedown',
    wx.WXK_F10: 'F10',
    wx.WXK_END: 'End',
    wx.WXK_F15: 'F15',
    wx.WXK_UP: 'Up',
    wx.WXK_SEPARATOR: 'Separator',
    wx.WXK_NUMPAD_ENTER: 'Numpad Enter',
    wx.WXK_NUMPAD_UP: 'Numpad Up',
    wx.WXK_PAGEUP: 'Pageup',
    wx.WXK_F3: 'F3',
    wx.WXK_F2: 'F2',
    wx.WXK_F1: 'F1',
    wx.WXK_F6: 'F6',
    wx.WXK_F5: 'F5',
    wx.WXK_F4: 'F4',
    wx.WXK_F9: 'F9',
    wx.WXK_F8: 'F8',
    wx.WXK_NUMPAD_DIVIDE: 'Numpad Divide',
    wx.WXK_NUMPAD9: 'Numpad9',
    wx.WXK_NUMPAD8: 'Numpad8',
    wx.WXK_NUMPAD3: 'Numpad3',
    wx.WXK_NUMPAD2: 'Numpad2',
    wx.WXK_NUMPAD1: 'Numpad1',
    wx.WXK_NUMPAD0: 'Numpad0',
    wx.WXK_NUMPAD7: 'Numpad7',
    wx.WXK_NUMPAD6: 'Numpad6',
    wx.WXK_NUMPAD4: 'Numpad4',
    wx.WXK_WINDOWS_MENU: 'Windows Menu',
    wx.WXK_NUMPAD_SPACE: 'Numpad Space',
    wx.WXK_NUMPAD_EQUAL: 'Numpad Equal',
    wx.WXK_NUMPAD_RIGHT: 'Numpad Right',
    wx.WXK_WINDOWS_LEFT: 'Windows Left',
    wx.WXK_RETURN: 'Return',
    wx.WXK_CONTROL: 'Control',
    wx.WXK_SPECIAL18: 'Special18',
    wx.WXK_HOME: 'Home',
    wx.WXK_SPECIAL12: 'Special12',
    wx.WXK_SPECIAL13: 'Special13',
    wx.WXK_SPECIAL10: 'Special10',
    wx.WXK_SPECIAL11: 'Special11',
    wx.WXK_SPECIAL16: 'Special16',
    wx.WXK_SPECIAL17: 'Special17',
    wx.WXK_SPECIAL14: 'Special14',
    wx.WXK_SPECIAL15: 'Special15',
    wx.WXK_HELP: 'Help',
    wx.WXK_SPECIAL19: 'Special19',
    wx.WXK_NUMPAD_END: 'Numpad End',
    wx.WXK_NUMPAD_PAGEUP: 'Numpad Pageup',
    wx.WXK_NUMPAD_MULTIPLY: 'Numpad Multiply',
    wx.WXK_DELETE: 'Delete',
    wx.WXK_SPECIAL20: 'Special20',
    wx.WXK_PAUSE: 'Pause',
    wx.WXK_CANCEL: 'Cancel',
    wx.WXK_ADD: 'Add',
    wx.WXK_NUMPAD_F1: 'Numpad F1',
    wx.WXK_NUMPAD_DELETE: 'Numpad Delete',
    wx.WXK_MBUTTON: 'Mbutton',
    wx.WXK_TAB: 'Tab',
    wx.WXK_NUMPAD_DOWN: 'Numpad Down',
    wx.WXK_ESCAPE: 'Escape',
    wx.WXK_NUMLOCK: 'Numlock',
    wx.WXK_LEFT: 'Left',
    wx.WXK_PRIOR: 'Prior',
    wx.WXK_NUMPAD_INSERT: 'Numpad Insert',
    wx.WXK_EXECUTE: 'Execute',
    wx.WXK_START: 'Start',
    wx.WXK_F19: 'F19',
    wx.WXK_F18: 'F18',
    wx.WXK_F13: 'F13',
    wx.WXK_F12: 'F12',
    wx.WXK_F11: 'F11',
    wx.WXK_F17: 'F17',
    wx.WXK_F16: 'F16',
    wx.WXK_F14: 'F14',
    wx.WXK_RIGHT: 'Right',
    wx.WXK_NUMPAD5: 'Numpad5',
    wx.WXK_BACK: 'Back',
    wx.WXK_RBUTTON: 'Rbutton',
    wx.WXK_SUBTRACT: 'Subtract',
    wx.WXK_NUMPAD_F4: 'Numpad F4',
    wx.WXK_NUMPAD_F2: 'Numpad F2',
    wx.WXK_NUMPAD_F3: 'Numpad F3',
    wx.WXK_NUMPAD_ADD: 'Numpad Add',
    wx.WXK_MULTIPLY: 'Multiply',
    wx.WXK_F7: 'F7',
    wx.WXK_NUMPAD_PAGEDOWN: 'Numpad Pagedown',
    wx.WXK_DECIMAL: 'Decimal',
    wx.WXK_NUMPAD_BEGIN: 'Numpad Begin',
    wx.WXK_NUMPAD_SUBTRACT: 'Numpad Subtract',
    wx.WXK_F22: 'F22',
    wx.WXK_F23: 'F23',
    wx.WXK_F20: 'F20',
    wx.WXK_F21: 'F21',
    wx.WXK_F24: 'F24',
    wx.WXK_NUMPAD_LEFT: 'Numpad Left',
    wx.WXK_LBUTTON: 'Lbutton',
    wx.WXK_WINDOWS_RIGHT: 'Windows Right',
    wx.WXK_DIVIDE: 'Divide',
    wx.WXK_PRINT: 'Print',
}

# keys which go to EVT_CHAR but aren't printable...
non_alphanumeric = set([
    wx.WXK_DELETE,
    wx.WXK_PAGEDOWN,
    wx.WXK_PAGEUP,
    wx.WXK_TAB,
    wx.WXK_ESCAPE,
    wx.WXK_NUMPAD_SPACE,
    wx.WXK_NUMPAD_TAB,
    wx.WXK_NUMPAD_ENTER,
    wx.WXK_NUMPAD_F1,
    wx.WXK_NUMPAD_F2,
    wx.WXK_NUMPAD_F3,
    wx.WXK_NUMPAD_F4,
    wx.WXK_NUMPAD_HOME,
    wx.WXK_NUMPAD_LEFT,
    wx.WXK_NUMPAD_UP,
    wx.WXK_NUMPAD_RIGHT,
    wx.WXK_NUMPAD_DOWN,
    wx.WXK_NUMPAD_PAGEUP,
    wx.WXK_NUMPAD_PAGEDOWN,
    wx.WXK_NUMPAD_END,
    wx.WXK_NUMPAD_BEGIN,
    wx.WXK_NUMPAD_INSERT,
    wx.WXK_NUMPAD_DELETE,
    wx.WXK_NUMPAD_EQUAL,
    wx.WXK_NUMPAD_MULTIPLY,
    wx.WXK_NUMPAD_ADD,
    wx.WXK_NUMPAD_SEPARATOR,
    wx.WXK_NUMPAD_SUBTRACT,
    wx.WXK_NUMPAD_DECIMAL,
    wx.WXK_NUMPAD_DIVIDE,
])

if os.name == 'nt':
    non_alphanumeric.update([wx.WXK_WINDOWS_LEFT, wx.WXK_WINDOWS_RIGHT, wx.WXK_WINDOWS_MENU])

# include all the function keys
non_alphanumeric.update((getattr(wx, 'WXK_F' + str(x)) for x in xrange(1, 13)))

