#__LICENSE_GOES_HERE__

test_contact_order = \
{'SpecialGroup_fakerootgroup': [u'digsby/kevin@digsby.org/steve@digsby.org',
                                u'gtalk/kevin@symbolsystem.com/digsby03@jabber.org',
                                u'gtalk/kevin@symbolsystem.com/digsby04@jabber.org',
                                u'gtalk/kevin@digsby.com/digsby04@jabber.org'],
 u'a': [],
 u'aol buddies': ['aim/digsby01/dotsyntaxdigsby',
                  'aim/digsby01/499895879',
                  'aim/digsby01/shaps776@gmail.com'],
 u'contacts': [u'digsby/kevin@digsby.org/steve@digsby.org',
               u'gtalk/kevin@symbolsystem.com/digsby03@jabber.org',
               u'gtalk/kevin@symbolsystem.com/digsby04@jabber.org',
               u'gtalk/kevin@digsby.com/digsby04@jabber.org'],
 u'd': ['aim/digsby01/digsby03',
        'aim/digsby01/digsby13',
        'aim/digsby01/someone',
        'aim/digsby01/slavachka'],
 u'digsbies': ['aim/digsby01/shaps776', 'aim/digsby01/[digsbies]'],
 u'digsbies 1': ['aim/digsby01/synae00',
                 'aim/digsby01/[digsbies1]',
                 'aim/digsby01/digsby04'],
 u'digsby buddies': ['aim/digsby01/digsby01',
                     'aim/digsby01/smarterchild',
                     'aim/digsby01/digsby08',
                     'aim/digsby01/499895879',
                     'aim/digsby01/227512155',
                     'aim/digsby01/230391135',
                     'aim/digsby01/dotsyntax1',
                     'aim/digsby01/kollivier2000',
                     'aim/digsby01/brokenhalo282',
                     'aim/digsby01/455528135',
                     'aim/digsby01/366800300',
                     'aim/digsby01/digsby13',
                     'aim/digsby01/250918398'],
 u'dotsyntax': [u'digsby/kevin@digsby.org/aaron@digsby.org',
                u'digsby/kevin@digsby.org/chris@digsby.org',
                u'digsby/kevin@digsby.org/steve@digsby.org',
                u'digsby/kevin@digsby.org/awesome@digsby.org',
                u'digsby/kevin@digsby.org/mike@digsby.org',
                u'digsby/kevin@digsby.org/notjeffrey@digsby.org',
                u'digsby/kevin@digsby.org/jeffrey@digsby.com',
                u'gtalk/kevin@digsby.com/chris@digsby.com',
                u'gtalk/kevin@digsby.com/awesome@digsby.org',
                u'gtalk/kevin@digsby.com/kevin@digsby.org',
                u'gtalk/kevin@digsby.com/kevin@digsby.com',
                u'gtalk/kevin@digsby.com/brok3nhalo@gmail.com',
                u'gtalk/kevin@digsby.com/steve@digsby.com',
                u'gtalk/kevin@digsby.com/kevin@symbolsystem.com',
                u'gtalk/kevin@digsby.com/mike.dougherty@gmail.com',
                u'Metacontact #1',
                u'gtalk/kevin@digsby.com/mike@digsby.com',
                u'gtalk/kevin@digsby.com/jeffrey@digsby.com',
                u'gtalk/kevin@digsby.com/kollivier@digsby.com',
                u'gtalk/kevin@digsby.com/jeffrey.rogiers@gmail.com',
                u'Metacontact #5',
                u'gtalk/kevin@digsby.com/stelminator@gmail.com',
                u'Metacontact #2',
                u'Metacontact #4',
                u'gtalk/kevin@symbolsystem.com/kevin@digsby.com',
                u'gtalk/kevin@symbolsystem.com/steve@dotsyntax.com',
                u'Metacontact #0',
                u'gtalk/kevin@symbolsystem.com/brok3nhalo@gmail.com',
                u'gtalk/kevin@symbolsystem.com/kevinwatters@gmail.com',
                u'gtalk/kevin@symbolsystem.com/digsby05@jabber.org',
                u'gtalk/kevin@symbolsystem.com/kevin@symbolsystem.com',
                u'gtalk/kevin@symbolsystem.com/mike.dougherty@gmail.com',
                u'gtalk/kevin@symbolsystem.com/digsby01@jabber.org',
                u'gtalk/kevin@symbolsystem.com/shaps776@gmail.com',
                u'Metacontact #3',
                u'gtalk/kevin@symbolsystem.com/jeffrey.rogiers@gmail.com',
                'aim/digsby01/stelminator3',
                'aim/digsby01/czeb670',
                'aim/digsby01/ktw6675',
                'aim/digsby01/stelminator',
                'aim/digsby01/synae00',
                'aim/digsby01/wsj',
                'aim/digsby01/digsby01',
                'aim/digsby01/newname',
                'aim/digsby01/steve@dotsyntax.com',
                'aim/digsby01/366800300',
                'aim/digsby01/dotsyntax1337'],
 u'general': [],
 u'root': [],
 u'users': [u'gtalk/kevin@digsby.com/nachtien@gmail.com',
            u'gtalk/kevin@digsby.com/zathman@gmail.com'],
 u'\xa7\xa7\xa7\u05d9\u05e7\u0e30\u0e1f\u0e23 \u0e23\u0e37 \ufffd': [],
 u'\u0430\u0432\u043e\u044b\u0434\u0444\u0430\u043e\u0444\u0432\u043b': ['aim/digsby01/maf54',
                                                                         'aim/digsby01/499895879',
                                                                         'aim/digsby01/penultimatefire',
                                                                         'aim/digsby01/digsby01new',
                                                                         'aim/digsby01/o00entity00o']}
