from __future__ import with_statement
if __name__ == '__main__':

    import sys, os, os.path
    path = os.path.join(sys.path[0], 'snac')

    def write(snacs):
        for fam, d in snacs.iteritems():
            filename = os.path.join(path, 'family_x%02x.py' % fam)
            with open(filename, 'w') as f:
                for sub, desc in sorted(d.items()):
                   if type(sub) is int:
                       s = """
def x%(fam)02x_x%(sub)02x(o, sock, data):
    '''
    SNAC (x%(fam)x, x%(sub)x): %(desc)s

    reference: U{http://iserverd.khstu.ru/oscar/snac_%(fam)02x_%(sub)02x.html}
    '''
    raise NotImplementedError
    """
                       f.write( s % dict(fam=fam, sub=sub, desc=desc))
                   else:
                       f.write('\nx%02x_%s="%s"' % (fam, sub, desc))

    snacs = {
             # Please note it is generally the case that even
             # subtypes are sent by the client, odd subtypes are
             # sent by the server
           0x0001    :    {'name'    :    'Generic',
                           0x01      :    'Generic Family Error',
                           0x02      :    'Client ready',
                           0x03      :    'Server ready',
                           0x04      :    'New service request',
                           0x05      :    'Service redirect',
                           0x06      :    'Rate limit request',
                           0x07      :    'Rate limit information',
                           0x08      :    'Rate info acknowledgement',
                           0x09      :    '0x1, 0x9: Server deleted a rate group and you didn\'t handle it',
                           0x0a      :    'Rate info change',
                           0x0b      :    'Server pause',
                           0x0c      :    'Client pause ack',
                           0x0d      :    'Server resume',
                           0x0e      :    'Request self info',
                           0x0f      :    'Self info reply',
                           0x10      :    '0x1, 0x10: You\'ve been eviled!',
                           0x11      :    'Set idle time',
                           0x12      :    'Server migration notice and information',
                           0x13      :    "Got message of the day",
                           0x14      :    'Set privacy flags',
                           0x15      :    'Well-known URLs',
                           0x16      :    'NOP (keep-alive packet)',
                           0x17      :    'Request server services versions',
                           0x18      :    'Server service versions response',
                           0x1e      :    'Set status/location info (also for direct connect info)',
                           0x1f      :    'Evil AIM prove yourself packet',
                           0x20      :    'Response to prove yourself',
                           0x21      :    'Extended status info (buddy icon)',
                           },
           0x0002    :    {'name'    :    'Location',
                           0x01      :    'Location Family Error',
                           0x02      :    'Request limitation params for Location group',
                           0x03      :    'Location limitations response',
                           0x04      :    'Set user info',
                           0x05      :    'Request user info',
                           0x06      :    'Requested User information',
                           0x07      :    'Watcher sub request (??)',
                           0x08      :    'Watcher notification',
                           0x09      :    'Request to Update directory info',
                           0x0a      :    'Reply to update directory info',
                           0x0b      :    'Unknown info request',
                           0x0c      :    'Unknown info response (may contain tlv)',
                           0x0f      :    'Update user directory interests',
                           0x10      :    'User directory interest reply',
                           0x15      :    'User info query',
                           },
           0x0003    :    {'name'    :    'Buddy List management',
                           0x01      :    'Buddy List management Family Error',
                           0x02      :    'Request BLM params',
                           0x03      :    'BLM limits response',
                           0x04      :    'add buddy to list',
                           0x05      :    'remove buddy from list',
                           0x06      :    'query for list of watchers (supported?)',
                           0x07      :    'watcher list response',
                           0x08      :    'watcher sub request (wtf is this?)',
                           0x09      :    'watcher notification',
                           0x0a      :    'Notification rejected!',
                           0x0b      :    'Oncoming buddy',
                           0x0c      :    'Offgoing buddy',
                           },
           0x0004    :    {'name'    :    'ICBM',
                           0x01      :    'ICBM Family Error',
                           0x02      :    'Set ICBM params',
                           0x03      :    'Reset ICBM params',
                           0x04      :    'Request ICBM params',
                           0x05      :    'Messaging limits',
                           0x06      :    'Outgoing message',
                           0x07      :    'Incoming message',
                           0x08      :    'Evil request',
                           0x09      :    'Server evil ack',
                           0x0a      :    'Msg not delivered',
                           0x0b      :    'client/server message error (or data!)',
                           0x0c      :    'Server message ack',
                           0x14      :    'MTN',
                           },
           0x0005    :    {'name'    :    'ads - deprecated',
                           0x01      :    'ads Family Error',
                           0x02      :    'Request ads',
                           0x03      :    'Ads response',
                           },
           0x0006    :    {'name'    :    'Invite',
                           0x01      :    'Invite Family Error',
                           0x02      :    'Invite a friend',
                           0x03      :    'Invitation ack',
                           },
           0x0007    :    {'name'    :    'Admin - this seems to be down',
                           0x01      :    'Admin Family Error',
                           0x02      :    'Request account info',
                           0x03      :    'Requested account info',
                           0x04      :    'Request change account info',
                           0x05      :    'Change account info ack',
                           0x06      :    'Account confirm request',
                           0x07      :    'account confirm response',
                           0x08      :    'account delete request',
                           0x09      :    'Account delete ack',
                           },
           0x0008    :    {'name'    :    'Popup',
                           0x01      :    'Popup Family Error',
                           0x02      :    'Display popup',
                           },
           0x0009    :    {'name'    :    'Privacy management',
                           0x01      :    'Privacy management Family Error',
                           0x02      :    'Request privacy params',
                           0x03      :    'Privacy limits response',
                           0x04      :    'Set group permissions',
                           0x05      :    'Add to visible list',
                           0x06      :    'Delet from visible list',
                           0x07      :    'Add to invisible list',
                           0x08      :    'Delete from invisible list',
                           0x09      :    'Service error',
                           0x0a      :    'Add to visible(?)',
                           0x0b      :    'Delete from visible(?)',
                           },
           0x000a    :    {'name'    :    'User lookup',
                           0x01      :    'User lookup Family Error',
                           0x02      :    'Search by email',
                           0x03      :    'Search response',
                           },
           0x000b    :    {'name'    :    'Usage stats',
                           0x01      :    'Usage stats Family Error',
                           0x02      :    'Set minimum report interval',
                           0x03      :    'Usage stats report',
                           0x04      :    'Stats report ack',
                           },
           0x000c    :    {'name'    :    'Translation - deprecated',
                           0x01      :    'Translation Family Error',
                           0x02      :    'client translate request',
                           0x03      :    'translate response',
                           },
           0x000d    :    {'name'    :    'Chat nav',
                           0x01      :    'Chat nav Family Error',
                           0x02      :    'Request limits',
                           0x03      :    'Request exchange info',
                           0x04      :    'Request room info',
                           0x05      :    'Request extended room info',
                           0x06      :    'Request member list',
                           0x07      :    'Search for room',
                           0x08      :    'Create room',
                           0x09      :    'Chat navigation info',
                           },
           0x000e    :    {'name'    :    'Chat',
                           0x01      :    'Chat Family Error',
                           0x02      :    'Chat room info update',
                           0x03      :    'User joined chat room',
                           0x04      :    'User left chat room',
                           0x05      :    'Outgoing chat message',
                           0x06      :    'Incoming chat message',
                           0x07      :    'Evil request',
                           0x08      :    'Evil response',
                           0x09      :    'Chat error or data',
                           0x26      :    'Chat room info?',
                           0x30      :    'Room list?',
                           },
           0x000f    :    {'name'    :    'Directory user search',
                           0x01      :    'Directory user search Family Error',
                           0x02      :    'Client search request',
                           0x03      :    'Search reply',
                           0x04      :    'Request interests list',
                           0x05      :    'Interest list response',
                           },
           0x0010    :    {'name'    :    'SSBI',
                           0x01      :    'SSBI Family Error',
                           0x02      :    'Upload your icon',
                           0x03      :    'Upload buddy icon reply',
                           0x04      :    'Request buddy icon',
                           0x05      :    'Requested buddy icon',
                           0x06      :    'SNAC(0x10, 0x06)',
                           0x07      :    'SNAC(0x10, 0x07)',
                           },
           0x0013    :    {'name'    :    'SSI',
                           0x01      :    'SSI Family Error',
                           0x02      :    'Request SSI params',
                           0x03      :    'SSI Limitations',
                           0x04      :    'Request contact list (first time)',
                           0x05      :    'Contact list request',
                           0x06      :    'Server contact list reply',
                           0x07      :    'Request contact list (after login)',
                           0x08      :    'SSI add item',
                           0x09      :    'SSI modify item',
                           0x0a      :    'SSI delete item',
                           0x0e      :    'SSI acknowledgement',
                           0x0f      :    'client local SSI is up-to-date',
                           0x11      :    'Contact edit start',
                           0x12      :    'Contact edit end',
                           0x14      :    'Grant future authorization to client',
                           0x15      :    'Future authorization granted',
                           0x16      :    'Delete yourself from another list (supported?)',
                           0x18      :    'Send authorization request',
                           0x19      :    'Authorization request ack',
                           0x1a      :    'Send authorization reply',
                           0x1b      :    'Authorization reply ack',
                           0x1c      :    '"You were added" message',
                           },
           0x0015    :    {'name'    :    'ICQ extensions',
                           0x01      :    'ICQ extensions Family Error',
                           0x02      :    'Meta info request',
                           0x03      :    'Meta info response',
                           },
           0x0017    :    {'name'    :    'Authorization',
                           0x01      :    'Authorization Family Error',
                           0x02      :    'Client login request (md5)',
                           0x03      :    'Server login response (md5)',
                           0x04      :    'Request new screen name',
                           0x05      :    'New screen name response',
                           0x06      :    'Client signon request',
                           0x07      :    'Server logon response',
                           0x0a      :    'Server SecureID request',
                           0x0b      :    'Client SecureID response',
                           },
           0x0085    :    {'name'    :    'Broadcast',
                           0x01      :    'Broadcast Family Error',
                           0x02      :    'Send broadcast message to server',
                           0x03      :    'Server broadcast reply',
                           },
           }
    write(snacs)