rpm = {
 1 : 0, #'Other', #VM?
 2 : .25, #'Unknown',
# 3 : .5, #'Desktop',
# 4 : .5, #'Low Profile Desktop',
# 5 : .5, #'Pizza Box',
# 6 : .5, #'Mini Tower',
# 7 : .5, #'Tower',
 8 : .25, #'Portable',
 9 : .25, #'Laptop',
 10 : .25, #'Notebook',
 11 : 0, #'Hand Held',
 12 : .25, #'Docking Station',
# 13 : .5, #'All in One',
 14 : .2, #'Sub Notebook',
# 15 : .5, #'Space-Saving',
# 16 : .5, #'Lunch Box',
# 17 : .5, #'Main System Chassis',
# 18 : .5, #'Expansion Chassis',
# 19 : .5, #'SubChassis',
# 20 : .5, #'Bus Expansion Chassis',
# 21 : .5, #'Peripheral Chassis',
# 22 : .5, #'Storage Chassis',
# 23 : .5, #'Rack Mount Chassis',
# 24 : .5, #'Sealed-Case PC'
}
#{
# 1 : 'Other',
# 2 : 'Unknown',
# 3 : 'Desktop',
# 4 : 'Low Profile Desktop',
# 5 : 'Pizza Box',
# 6 : 'Mini Tower',
# 7 : 'Tower',
# 8 : 'Portable',
# 9 : 'Laptop',
# 10 : 'Notebook',
# 11 : 'Hand Held',
# 12 : 'Docking Station',
# 13 : 'All in One',
# 14 : 'Sub Notebook',
# 15 : 'Space-Saving',
# 16 : 'Lunch Box',
# 17 : 'Main System Chassis',
# 18 : 'Expansion Chassis',
# 19 : 'SubChassis',
# 20 : 'Bus Expansion Chassis',
# 21 : 'Peripheral Chassis',
# 22 : 'Storage Chassis',
# 23 : 'Rack Mount Chassis',
# 24 : 'Sealed-Case PC'
#}
