# Alerts pop up messages (Note. some are missing)

popup_strings = {
    'action_slots'                     : {'string' : _('Action Slots bonus'),
                                          'link'   : 'apps/actionslots.html'},
    'action_tabs'                      : {'string' : _('Action Tabs bonus'),
                                          'link'   : 'apps/actiontabs.html'},
    'birthdays'                        : {'string' : _('Upcoming birthday'),
                                          'link'   : 'birthdays.html'},
    'cafe_food_ready'                  : {'string' : _('Food is ready to serve'),
                                          'link'   : 'apps/cafe.html?source=A&type=R'},
    'cafe_food_rotting'                : {'string' : _('Food is rotting'),
                                          'link'   : 'apps/cafe.html?source=A&type=O'},
    'cafe_needs_love'                  : {'string' : _('Your Cafe needs love'),
                                          'link'   : 'apps/cafe.html?source=A&type=L'},
    'cafe_visit'                       : {'string' : _('Your Cafe is open!'),
                                          'link'   : 'apps/cafe.html?source=A&type=V'},
    'cafe_visit_clean'                 : {'string' : _('Someone helped you'),
                                          'link'   : 'apps/cafe.html?source=A&type=C'},
    'cafe_visit_eat'                   : {'string' : _('Someone left you a tip'),
                                          'link'   : 'apps/cafe.html?source=A&type=E'},
    'cafe_waiter_contract_expired'     : {'string' : _('Cafe contract expired'),
                                          'link'   : 'apps/cafe.html?source=A&type=X'},
    'comments'                         : {'string' : _('New comment'),
                                          'link'   : ''},
    'cr_photo_warning'                 : {'string' : _('Photo Violation'),
                                          'link'   : 'rejected_photos.html'},
    'elections_job_completed'          : {'string' : _('Collect your funds'),
                                          'link'   : 'apps/elections.html?so=a0'},
    'elections_favor'                  : {'string' : _('Thank your collaborator'),
                                          'link'   : 'apps/elections.html?so=a1'},
    'elections_hired'                  : {'string' : _("You've been hired!"),
                                          'link'   : 'apps/elections.html?so=a2'},
    'elections_new_round'              : {'string' : _('New Elections round!'),
                                          'link'   : 'apps/elections.html?so=a3'},
    'elections_promo'                  : {'string' : _('New Game! Play Elections!'),
                                          'link'   : 'apps/elections.html?so=a4'},
    'farm_ready'                       : {'string' : _('Crops are ready to harvest!'),
                                          'link'   : 'farm.html'},
    'farm_visit'                       : {'string' : _('Visit your Farm'),
                                          'link'   : 'farm.html'},
    'find_friend'                      : {'string' : _('Find more friends'),
                                          'link'   : 'friends.html?source=findalert#tab=3'},
    'new_friends'                      : {'string' : _('New friend'),
                                          'link'   : 'friends.html?new_friends=1#tab=0&type=0&filterpg=New_0'},
    'friend_requests'                  : {'string' : _('New friend request'),
                                          'link'   : 'friends.html#tab=2'},
    'gifts'                            : {'string' : _('New gift'),
                                          'link'   : 'gifts.html#t=t1'},
    'gold_2'                           : {'string' : _('New Gold offers'),
                                          'link'   : 'gold.html?ll=digsby_alerts#t=tearn_gold'},
    'groups_updated'                   : {'string' : _('Groups updated'),
                                          'link'   : 'groups.html#h=1_0_0'},
    'group_forum_reply'                : {'string' : _('Forum topic replies'),
                                          'link'   : 'my_forum_topics.html#h=0_0_0_0_0'},
    'group_invite'                     : {'string' : _('New group invite'),
                                          'link'   : 'group_invites.html'},
    'invite_friend'                    : {'string' : _('New invite to send'),
                                          'link'   : 'friends.html?source=invitealert#tab=contacts'},
    'luv'                              : {'string' : _('New Luv'),
                                          'link'   : 'luv.html'},
    'meetme_headliner_reup'            : {'string' : _('Headliner Reup'),
                                          'link'   : ''},
    'meetme_spotlight_reup'            : {'string' : _('Spotlight Reup'),
                                          'link'   : ''},
    'meetme_match'                     : {'string' : _('New Meet Me match'),
                                          'link'   : 'meetme.html?match=1#t=t2&y=0&m=0'},
    'meetme_yes'                       : {'string' : _('Meet Me interests'),
                                          'link'   : 'meetme.html'},
    'unread_messages'                  : {'string' : _('New message'),
                                          'link'   : 'messages.html'},
    'mob_boost'                        : {'string' : _('Mafia booster ready!'),
                                          'link'   : 'apps/mafia.html?source=B'},
    'mob_fight'                        : {'string' : _('New Mafia fight'),
                                          'link'   : 'apps/mafia.html?source=F#h=/fight/fight_enemies'},
    'mob_hire'                         : {'string' : _('New Mafia boss'),
                                          'link'   : 'apps/mafia.html?source=H#h=/character'},
    'mob_promo'                        : {'string' : _('New Mafia jobs'),
                                          'link'   : 'apps/mafia.html?source=P'},
    'mob_promo_simple'                 : {'string' : _('New Mafia jobs'),
                                          'link'   : 'apps/mafia.html?source=Z'},
    'mob_prop_rdy'                     : {'string' : _('Mafia property ready'),
                                          'link'   : 'apps/mafia.html?source=R#h=/properties'},
    'mobile_new_update'                : {'string' : _('New Mobile Update'),
                                          'link'   : 'tagged_mobile.html'},
    'pending_comment'                  : {'string' : _('New pending comment'),
                                          'link'   : 'view_comments.html#t=pending_1'},
    'pets'                             : {'string' : _('Pets updates'),
                                          'link'   : 'pets.html'},
    'photo_comments'                   : {'string' : _('New photo comment'),
                                          'link'   : 'notifications.html'},
    'poker_2'                          : {'string' : _('Bonus poker chips'),
                                          'link'   : 'poker.html'},
    'profile_photo'                    : {'string' : _('No profile photo!'),
                                          'link'   : 'add_photo_interstitial.html'},
    'profile_viewers'                  : {'string' : _('New profile viewer'),
                                          'link'   : 'friends.html#tab=5'},
    'questions_answer'                 : {'string' : _('New answer'),
                                          'link'   : 'questions.html?tab=answer'},
    'questions'                        : {'string' : _('New question'),
                                          'link'   : 'questions.html?tab=my_questions'},
    'sororitylife'                     : {'string' : _('New Sorority events'),
                                          'link'   : 'sororitylife.html'},
    'sororitylife_new_version'         : {'string' : _('Sorority: new version'),
                                          'link'   : 'sororitylife.html'},
    'tags'                             : {'string' : _('New Tag'),
                                          'link'   : 'tags.html#t=t1&mt=0_0&st=0_All_0'},
    'topics_promo'                     : {'string' : _('New Topics for you'),
                                          'link'   : 'conversations.html?source=lp'},
    'topics_new'                       : {'string' : _('Conversations for you'),
                                          'link'   : 'conversations.html?source=ln'},
    'topics_response'                  : {'string' : _('New conversation post'),
                                          'link'   : 'conversations.html?source=lr'},
    'videos'                           : {'string' : _('New shared video'),
                                          'link'   : 'http://video.tag-local.com/#op=to_you'},
    'wink'                             : {'string' : _('New wink'),
                                          'link'   : 'wink.html'},
    'zoosk_coin'                       : {'string' : _('Free Zoosk coins'),
                                          'link'   : 'apps/zoosk.html?z_page=home.php&from=digsby-coinalert&api_signature=8e49b20dcf4f6eeded15553909608617'},
    'zoosk_message'                    : {'string' : _('New Zoosk messages'),
                                          'link'   : 'apps/zoosk.html?z_page=inbox.php&from=digsby-flirtalert&api_signature=233cd9eb02f9a19d427ebac3f511dda4'}
}