import os
import sipconfig

#CAS: this is a win32 version, specific to my machine, provided for example.

# The name of the SIP build file generated by SIP and used by the build
# system.
build_file = "blist.sbf"

# Get the SIP configuration information.
config = sipconfig.Configuration()

# Run SIP to generate the code.
os.system(" ".join([config.sip_bin, "-c", ".", "-b", build_file, "sip/blist.sip"]))

# Create the Makefile.
makefile = sipconfig.SIPModuleMakefile(config, build_file)

# Add the library we are wrapping.  The name doesn't include any platform
# specific prefixes or extensions (e.g. the "lib" prefix on UNIX, or the
# ".dll" extension on Windows).
makefile.extra_libs = ['buddylist']
makefile.extra_include_dirs.append(r'C:\Users\Christopher\workspace\boost_1_42_0')
makefile.extra_cxxflags.append('//EHsc')
makefile.extra_lib_dirs.extend([r'C:\Users\Christopher\workspace\digsby\ext\src\BuddyList\msvc2008\Release'])

makefile._build['objects'] += " PythonInterface.obj FileUtils.obj"
makefile._build['sources'] += " PythonInterface.cpp FileUtils.cpp"

# Generate the Makefile itself.
makefile.generate()
