"""
List of error codes and the readable messages assocatiated

From U{http://msnpiki.msnfanatic.com/index.php/Reference:Error_List}
"""

codes = {
          None:None,
          100: 'Unknown',
          200: 'Invalid Syntax',
          201: 'Invalid parameter',
          205: 'Invalid principal',
          206: 'Domain name missing',
          207: 'Already logged in',
          208: 'Invalid principal',
          209: 'Nickname change illegal',
          210: 'Principal list full',
          213: 'Invalid rename request?',
          215: 'User already on list',
          216: 'User not on list',
          217: 'User not online',
          218: 'Already in mode',
          219: 'User is in the opposite list',
          223: 'Too many groups',
          224: 'Invalid group',
          225: 'User not in group',
          227: 'Group not empty',
          228: 'Group with same name already exists',
          229: 'Group name too long',
          230: 'Cannot remove group zero',
          231: 'Invalid group',
          240: 'Invalid RML/ADL command',
          280: 'Switchboard failed',
          281: 'Transfer to switchboard failed',
          282: 'P2P Error?',
          300: 'Required field missing',
          302: 'Not logged in',
          402: 'Error accessing contact list',
          403: 'Error accessing contact list',
          420: 'Invalid Account Permissions',
          500: 'Internal server error',
          501: 'Database server error',
          502: 'Command disabled',
          504: 'Service temporarily disabled',
          510: 'File operation failed',
          511: 'Banned',
          520: 'Memory allocation failed',
          540: 'Challenge response failed',
          600: 'Server is busy',
          601: 'Server is unavailable',
          602: 'Peer nameserver is down',
          603: 'Database connection failed',
          604: 'Server is going down',
          605: 'Server unavailable',
          700: 'Could not create connection',
          710: 'Bad CVR parameters sent',
          711: 'Write is blocking',
          712: 'Session is overloaded',
          713: 'Calling too rapidly',
          714: 'Too many sessions',
          715: 'Not expected',
          717: 'Bad friend file',
          731: 'Not expected',
          800: 'Requesting too often',
          910: 'Server too busy',
          911: 'Server is busy',
          912: 'Server too busy',
          913: 'Not allowed while invisible',
          914: 'Server unavailable',
          915: 'Server unavailable',
          916: 'Server unavailable',
          917: 'Authentication failed',
          918: 'Server too busy',
          919: 'Server too busy',
          920: 'Not accepting new principals',
          921: 'Server too busy',
          922: 'Server too busy',
          923: 'Kids\' Passport without parental consent',
          924: 'Passport account not yet verified',
          928: 'Bad ticket',
          }